/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author deede
 */
import java.awt.GridLayout;
import java.awt.PopupMenu;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JPanel;
public class Welcome extends javax.swing.JFrame {



    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        try {
            Button2 =(javax.swing.JButton)java.beans.Beans.instantiate(getClass().getClassLoader(), "Welcome_Button2");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (java.io.IOException e) {
            e.printStackTrace();
        }
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        JLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton3.setText("Show Report");

        jButton4.setText("Quit");

        JLabel1.setText("Welcome to EasyKanban.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addComponent(jButton3)
                            .addComponent(Button2))
                        .addGap(93, 241, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JLabel1)
                .addGap(48, 48, 48)
                .addComponent(Button2)
                .addGap(34, 34, 34)
                .addComponent(jButton3)
                .addGap(46, 46, 46)
                .addComponent(jButton4)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void showAddTaskDialog(PopupMenu taskStatusComboBox) {
    String input = JOptionPane.showInputDialog(null, "Enter the number of tasks:");
    if (input !=null) {
        try { 
            int numTasks = Integer.parseInt(input);
            if(numTasks > 0) {
                for (int i = 0; i < numTasks; i++) {
                JFrame dialog = new JFrame("Add Task");
                dialog.setSize(400, 300);
                dialog.setLocationRelativeTo(null);
                dialog.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
                JPanel panel = new JPanel ( new GridLayout(7, 2, 5, 5));
                 
                panel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
                
                JTextField taskNameField = new JTextField();
                JTextField taskDescription = new JTextField();
                JTextField developerDetailsField = new JTextField();
                JTextField durationField = new JTextField();
                
               
                
                
                panel.add(new JLabel("Task Name"));
                panel.add(taskNameField);
                panel.add(new JLabel("Task Description"));
                panel.add(taskDescription);
                panel.add(new JLabel("Developer Details"));
                panel.add(developerDetailsField);
                panel.add(new JLabel("Task Duration Hours"));
                panel.add(durationField);
                panel.add(new JLabel("Task Status"));
                panel.add(taskStatusComboBox); 
                     
               JButton submitButton = new JButton ("Submit") ;
               submitButton.addActionListener( new ActionListener() {
               @Override
               public void actionPerformed (ActionEvent e) {
                   String taskName;
                   String taskDescription;
                   String developerDetails; 
                   String durationInput =durationField.getText();
                   String taskStatus;
                   
                   if(taskName.isEmpty() || taskDescription.isEmpty() || developerDetails.isEmpty() || durationInput.isEmpty()) {
                     return;              
                            
                       
                     }
                   
               int taskDuration;
               try {
                   taskDuration = Integer.parseInt(durationInput);
                   
               }catch (NumberFormatException ex) {
                   JOptionPane.showMessageDialog(null, "Please enter a valid number for task duration.");
                   return;
               }
               
              Task task = new Task (taskName, taskDescription, developerDetails, taskDuration, taskStatus);
              String[] developer = null;
                      int taskCounter =0; 
                      developer[taskCounter] = developerDetails;
                      String[] taskNames = null;
                      taskNames [taskCounter]= taskName;
                      String[] taskIDs = null;
                      taskIDs[taskCounter]= task.createTaskID();
                      int[] taskDurations = null;
                      taskDurations[taskCounter] = taskDuration;
                      String [] taskStatuses =null;
                      taskStatuses [taskCounter] = taskStatus;
                      
                      taskCounter++; // Icrement the task counter for the next task
                      
                      JOptionPane.showMessageDialog(null, task.printTaskDetails());
                      JOptionPane.showMessageDialog(null," Task successfully captured");
                      
                      dialog.dispose(); // Close the dialog
                      
                      
               
               
               panel.add(submitButton);
               dialog.add(panel);
               dialog.setVisible(true);
               
               }
               }else{
                       JOptionPane.showMessageDialog(null,"Number of tasks must be greater than zero.");
                       }
                } catch{NumberFormException ex) {
                        JOptionPane.showMessageDialog(null,"Please enter a valid number");
                        
                       
                        } 
                      
               JOptionPane.showMessageDialog(null, "Coming soon!");
                        
                        
                        
            //Quit application
                        
                        System.exit(0);
                              
                      
                      
                      
                
          
            
        
    

           
    /**
     * @param args the command line arguments
     */                              
                      
                      
                      
                
          
            
        
    

           
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button2;
    private javax.swing.JLabel JLabel1;
    public javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables
}
